/**
 * Korean for the **compiler-generated** labels: the text on an ability button,
 * the tail of a targeting prompt, and the title of a choice modal.
 *
 * These were left in English for the same reason the activity log originally
 * was — they are generated by the text→script compiler rather than authored —
 * but that turned out to be the argument *for* translating them, not against.
 * Generated text comes from a fixed vocabulary, so a table covers it. And this
 * is the last English on the board: a Korean player reads a fully Korean card
 * and then clicks a button labelled "Exhaust + 1 rune: ready a friendly unit".
 *
 * Three shapes, three entry points:
 *
 *   `Empower — 2⚡`                     → \`abilityLabelKo\`
 *   `↻: Deal 2 to a unit.`             → \`abilityLabelKo\` (cost half + effect half)
 *   `to give +2 Might this turn`       → \`targetLabelKo\`
 *   `Discard 2 cards`                  → \`choiceLabelKo\`
 *
 * The **effect half of an ability label is card rules text**, so it is handed
 * straight to `cardText.ts` rather than re-translated here. Only the cost half
 * and the fixed prompt vocabulary need tables of their own.
 *
 * Anything unmatched comes back `null` and the caller shows the English, which
 * is the same never-guess contract the rest of the i18n layer keeps.
 */

import { translateCardText } from './cardText'
import { numObj } from './korean'

/** `2⚡`, `↻`, `✦` are already glyphs by the time a label is built (`prettyCost`). */
const GLYPHS = /^[\d⚡✦↻\s,+]+$/

/**
 * Translate an effect fragment with the full card-text machinery rather than
 * the single-clause rules. Effect halves are routinely two sentences ("[Add]
 * 1⚡. If this is [Empowered], [Add] 2⚡ instead.") or carry a compound
 * ("Discard 1, then draw 1."), and only `translateCardText` runs the sentence
 * layer — triggers, compounds, "you may" — over each of them.
 *
 * All-or-nothing: a button reading half Korean and half English is worse than
 * one that is honestly English.
 */
function effectKo(frag: string, dropTruncatedTail = false): string | null {
  let segs = translateCardText(stripGlyphs(frag)).filter((x) => !x.neutral && !x.reminder)
  // The compiler elides an effect over 60 chars, which lops the last sentence
  // off mid-clause ("… If this is [Empowered]…"). That fragment can never
  // translate and must not veto the whole sentences before it.
  if (dropTruncatedTail && segs.length > 1 && !segs[segs.length - 1].translated) {
    segs = segs.slice(0, -1)
  }
  if (segs.length === 0 || !segs.every((x) => x.translated)) return null
  return segs.map((x) => x.text).join(' ')
}

// ── Cost fragments, as they appear left of the colon ──────────────────────
const COSTS: [RegExp, string][] = [
  [/^discard a gear$/i, '장비 하나 버리기'],
  [/^discard a card$/i, '카드 1장 버리기'],
  [/^discard (\d+)$/i, '카드 $1장 버리기'],
  [/^recycle (\d+) from (?:your )?trash$/i, '무덤에서 $1장 재활용'],
  [/^recycle (\d+) from your hand$/i, '손패에서 $1장 재활용'],
  [/^recycle (\d+)$/i, '$1장 재활용'],
  [/^disempower this$/i, '이 카드의 강화 해제'],
  [/^disempower me$/i, '나의 강화 해제'],
  [/^exhaust$/i, '소진'],
  [/^exhaust \+ (\d+) rune$/i, '소진 + 룬 $1개'],
  [/^pay the cost$/i, '비용 지불'],
]

function costKo(frag: string): string | null {
  const t = frag.trim()
  if (!t) return ''
  // A pure symbol run reads the same in both languages — pass it through.
  if (GLYPHS.test(t)) return t
  // Compound: "Discard a gear, 2⚡, ↻" — each comma-separated piece on its own.
  const parts = t.split(/\s*,\s*/)
  const out: string[] = []
  for (const part of parts) {
    if (GLYPHS.test(part)) {
      out.push(part)
      continue
    }
    // A leading [Keyword] stays English, as everywhere else.
    const kw = part.match(/^(\[[^\]]+\])\s*(.*)$/)
    const bare = kw ? kw[2] : part
    let hit: string | null = null
    for (const [re, ko] of COSTS) {
      const m = bare.match(re)
      if (m) {
        hit = ko.replace(/\$(\d)/g, (_, d) => m[Number(d)] ?? '')
        break
      }
    }
    if (!hit) return null
    out.push(kw ? `${kw[1]} ${hit}` : hit)
  }
  return out.join(', ')
}

// ── Target prompts — the "to …" tail of "Choose a unit to …" ──────────────
type Sub = string | ((m: RegExpMatchArray) => string)

const TARGETS: [RegExp, Sub][] = [
  [/^to counter it$/i, '무효화할 대상'],
  [/^to ready it$/i, '준비 상태로 만들 대상'],
  [/^to move$/i, '이동시킬 대상'],
  [/^to move it home and ready it$/i, '기지로 보내고 준비 상태로 만들 대상'],
  [/^to move it to the other battlefield and ready it$/i, '다른 전장으로 옮기고 준비 상태로 만들 대상'],
  [/^to send it back to base$/i, '기지로 돌려보낼 대상'],
  [/^to send back to base$/i, '기지로 돌려보낼 대상'],
  [/^to bounce it to its owner.s hand$/i, '주인의 손으로 되돌릴 대상'],
  [/^to bounce to its owner.s hand$/i, '주인의 손으로 되돌릴 대상'],
  [/^to deal (\d+)(?: damage)?$/i, (m) => `피해 ${numObj(m[1])} 줄 대상`],
  [/^to stun \((\d+) might in combat\)$/i, '[Stun]시킬 대상 (전투 시 위력 $1)'],
  [/^to give ([+−-])(\d+) might this turn$/i, (m) => `이번 턴 위력 ${numObj(m[1] + m[2])} 줄 대상`],
  [/^to give ([+−-])(\d+) might this turn \(([+−-])(\d+) if it stands alone\)$/i,
   (m) => `이번 턴 위력 ${numObj(m[1] + m[2])} 줄 대상 (혼자 있으면 ${m[3]}${m[4]})`],

  [/^to give ([+−-])(\d+) might$/i, (m) => `위력 ${numObj(m[1] + m[2])} 줄 대상`],
  // "[Assault 3]" is read with its number, so the particle follows the digit.
  [/^to grant \[([^\]]+?)(?: (\d+))?\]$/i,
   (m) => (m[2] ? `[${m[1]} ${m[2]}]${numObj(m[2]).slice(-1)} 줄 대상` : `[${m[1]}]을 줄 대상`)],
  [/^to attach to$/i, '부착할 대상'],
  [/^to pull here$/i, '여기로 끌어올 대상'],
  [/^to empower$/i, '강화할 대상'],
  [/^to empower or disempower$/i, '강화하거나 강화 해제할 대상'],
  [/^to swap might$/i, '위력을 맞바꿀 대상'],
  [/^with this one$/i, '이 카드와'],
  [/^to swap places with$/i, '자리를 맞바꿀 대상'],
]

/** Korean for a `TargetSpec.label`, or null to keep the English. */
export function targetLabelKo(label: string): string | null {
  const t = label.trim()
  for (const [re, ko] of TARGETS) {
    const m = t.match(re)
    if (m) return typeof ko === 'function' ? ko(m) : ko.replace(/\$(\d)/g, (_, d) => m[Number(d)] ?? '')
  }
  return null
}

// ── Choice-modal titles ───────────────────────────────────────────────────
const CHOICES: [RegExp, string][] = [
  // The optional extra-cost buttons above the hand (actions.ts `extraCostOptions`).
  [/^accelerate \((.+?)\): enter ready$/i, '[Accelerate] ($1): 준비된 채로 등장'],
  [/^pay additional \((.+?)\)$/i, '추가 비용 지불 ($1)'],
  [/^repeat \((.+?)\): resolve twice$/i, '[Repeat] ($1): 효과를 두 번 해결'],
  [/^repeat \((.+?)\)$/i, '[Repeat] ($1)'],
  [/^discard (\d+) cards?$/i, '카드 $1장을 버리세요'],
  [/^to (?:your|the enemy.s) base$/i, '기지로'],
  [/^to your base$/i, '내 기지로'],
  [/^to the enemy.s base$/i, '상대 기지로'],
  [/^to (.+)$/i, '$1(으)로'],
  [/^move (.+) — choose a destination$/i, '$1을(를) 어디로 옮길까요?'],
  [/^look at the top (\d+) — put (\d+) into your hand \(the rest recycle\)$/i,
   '맨 위 $1장을 봅니다 — $2장을 손패에 넣으세요 (나머지는 재활용)'],
  [/^predict (\d+) — choose cards to recycle to the bottom \(the rest stay on top\)$/i,
   '[Predict] $1 — 덱 맨 아래로 보낼 카드를 고르세요 (나머지는 맨 위에 남습니다)'],
  [/^return up to (\d+) unit\(s\) from trashes to their owners.? hands$/i,
   '무덤에서 최대 $1체의 유닛을 주인의 손으로 되돌립니다'],
  [/^ready up to (\d+) — units, gear and\/or runes$/i,
   '최대 $1개를 준비 상태로 — 유닛·장비·룬'],
  [/^choose a keyword to give me this turn$/i, '이번 턴 나에게 줄 키워드를 고르세요'],
  [/^(.+) \(gear\)$/i, '$1 (장비)'],
  [/^([a-z]+) rune$/i, '$1 룬'],
  [/^ravenbloom — take (.+) to hand\? \(skip = recycle\)$/i,
   'Ravenbloom — $1을(를) 손패로 가져올까요? (건너뛰면 재활용)'],
]

/** Korean for a `PendingChoice.label` or a choice option label. */
export function choiceLabelKo(label: string): string | null {
  const t = label.trim()
  for (const [re, ko] of CHOICES) {
    const m = t.match(re)
    if (m) return ko.replace(/\$(\d)/g, (_, d) => m[Number(d)] ?? '')
  }
  return null
}

// ── Activated-ability button labels ───────────────────────────────────────
const KEYWORD_ABILITY = /^(Empower|Equip)(?:\s*—\s*(.+))?$/i

/**
 * Korean for an `ActivatedAbility.label`.
 *
 * Two forms. `Empower — 2⚡` is a keyword and a cost, and the keyword stays
 * English like every other keyword on screen. `<cost>: <effect>` splits at the
 * **first** `": "` — the cost is always first, and the effect half may contain
 * a colon of its own (`Units here have "↻: Gain 1 XP."`).
 */
export function abilityLabelKo(label: string): string | null {
  const raw = label.trim()

  const kw = raw.match(KEYWORD_ABILITY)
  if (kw) return kw[2] ? `${kw[1]} — ${kw[2]}` : kw[1]

  // A `": "` does not prove a cost half. `Units here have "↻: Gain 1 XP."` is
  // one effect whose *quoted* ability carries the colon — splitting there gave
  // a nonsense cost of `Units here have "↻`. So the split is only taken when
  // the left side actually reads as a cost; otherwise the label is one effect.
  const div = raw.indexOf(': ')
  if (div > 0) {
    const cost = costKo(raw.slice(0, div))
    if (cost !== null) {
      const effRaw = raw.slice(div + 2).trim()
      const elided = effRaw.endsWith('…')
      const eff = effectKo(elided ? effRaw.slice(0, -1) : effRaw, elided)
      if (eff) return `${cost}: ${eff}${elided ? '…' : ''}`
    }
  }

  // Last resort: the whole label as one effect. `cardText` is more forgiving
  // than this module about a cost half it cannot read — it passes the English
  // through and translates the rest — which is right for a card's rules box but
  // wrong for a button. Reject anything that comes back still carrying English
  // prose, so the "never half-Korean" contract holds whichever path we took.
  const whole = effectKo(raw)
  return whole && !hasEnglishProse(whole) ? whole : null
}

/**
 * Two lowercase words in a row is English prose. Keyword brackets and card
 * names survive this on purpose: `[Empowered]` and `Ravenbloom` are single
 * capitalised tokens and are *meant* to stay English.
 */
function hasEnglishProse(s: string): boolean {
  return /[a-z]{2,}\s+[a-z]{2,}/.test(s.replace(/\[[^\]]*\]/g, ''))
}

/**
 * `prettyCost` has already rewritten the symbol tokens to glyphs by the time a
 * label exists, but `cardText.ts` matches on the tokens. Put them back so the
 * one set of rules serves both.
 */
function stripGlyphs(s: string): string {
  return s
    .replace(/(\d+)⚡/g, ':rb_energy_$1:')
    .replace(/↻/g, ':rb_exhaust:')
    .replace(/✦/g, ':rb_rune_rainbow:')
}
